### ISSUE TITLE
TypeError: ModelMixin._load_pretrained_model() missing 1 required positional argument: 'loaded_keys'

### ISSUE THREAD

**Issue by SaiZyca** [GiusTex/ComfyUI-DiffusersImageOutpaint#25]
need update code for diffusers

```
`Traceback (most recent call last):
  File "D:\_ComfyUI\ComfyUI\execution.py", line 347, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_ComfyUI\ComfyUI\execution.py", line 222, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_ComfyUI\ComfyUI\execution.py", line 194, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\_ComfyUI\ComfyUI\execution.py", line 183, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_ComfyUI\ComfyUI\custom_nodes\ComfyUI-DiffusersImageOutpaint\nodes.py", line 299, in sample
    last_rgb_latent = diffuserOutpaintSamples(model_path, controlnet_model, diffuser_outpaint_cnet_image, dtype, controlnet_path,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_ComfyUI\ComfyUI\custom_nodes\ComfyUI-DiffusersImageOutpaint\utils.py", line 143, in diffuserOutpaintSamples
    controlnet_model = loadControlnetModel(device, dtype, controlnet_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_ComfyUI\ComfyUI\custom_nodes\ComfyUI-DiffusersImageOutpaint\utils.py", line 106, in loadControlnetModel
    model, _, _, _, _ = ControlNetModel_Union._load_pretrained_model(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelMixin._load_pretrained_model() missing 1 required positional argument: 'loaded_keys'`
```

**Comment by GiusTex** [comment]
> need update code for diffusers

Thanks! I'll see what to do in the next days

**Comment by GiusTex** [comment]
Sorry! I already fixed it, I was stuck trying to get flux working; I'm uploading the fixed normal sdxl code now

**Comment by amirkerr** [comment]
> Sorry! I already fixed it, I was stuck trying to get flux working; I'm uploading the fixed normal sdxl code now

Thank you so much for your time and effort!

I just git clone the repo again and still get this error.

Do you need more info from me to help you fix it?

![Image](https://github.com/user-attachments/assets/fa9b6a67-b0f6-4b87-aacd-44185afbe9a8)

**Comment by amirkerr** [comment]
![Image](https://github.com/user-attachments/assets/5acde37b-52bc-46d7-8ab8-a22bcd73f53c)

**Comment by GiusTex** [comment]
> still get this error
> Do you need more info from me to help you fix it

I know, yesterday it worked, and now that I need to upload the fix it doesn't work; I'm working on it.


```
model, _, _, _, _ = ControlNetModel_Union._load_pretrained_model(
    controlnet_model, state_dict, model_file, "xinsir/controlnet-union-sdxl-1.0"
)
```
This is the fix, comes from https://huggingface.co/spaces/OzzyGT/diffusers-image-fill/blob/main/app.py#L28 that works, I was thinking if there was a way to avoid packing again the model and its config into a single folder

**Comment by amirkerr** [comment]
Sincerely appreciate your swift response!
Alas, I couldn't find app.py in DiffusersOutpaint custom nodes directory...

I think I have to wait for you to finish your update.

**Comment by GiusTex** [comment]
Did you get an error related to this app.py? I don't remember this file

**Comment by GiusTex** [comment]
Ahh
app.py is for gradio uis on huggingface, while for comfyui nodes I use nodes.py.
I'm changing a bit of code to use the model folder, since I cannot make it work taking bit and pieces from different places

**Comment by GiusTex** [comment]
It looks like the recent versions of those 2 libraries broke somethings; did reverting back work for you?

**Comment by amirkerr** [comment]
Yaaay! It works! Thank you soooo much! <3

Yes, reverting diffusers and transformers worked!
